import type {
  Activity,
  Agent,
  Automation,
  JarvisAdapter,
  JarvisSnapshot,
  MemoryItem,
  ToolItem,
} from "./types";

const activities: Activity[] = [
  {
    id: "l1",
    time: "Beispiel",
    source: "AI Core",
    level: "Info",
    message: "Beispiel einer abgeschlossenen Inferenz",
    context: "Prototypdaten, kein Runtime-Ereignis",
  },
  {
    id: "l2",
    time: "Beispiel",
    source: "Memory",
    level: "Info",
    message: "Beispiel eines Prüfungskandidaten",
    context: "Prototypdaten, kein Runtime-Ereignis",
  },
  {
    id: "l3",
    time: "Beispiel",
    source: "System",
    level: "Warnung",
    message: "Beispiel eines Diagnosehinweises",
    context: "Prototypdaten, kein Runtime-Ereignis",
  },
  {
    id: "l4",
    time: "Beispiel",
    source: "Agenten",
    level: "Info",
    message: "Beispiel einer Agentenaktivität",
    context: "Prototypdaten, kein Runtime-Ereignis",
  },
  {
    id: "l5",
    time: "Beispiel",
    source: "Voice",
    level: "Debug",
    message: "Beispiel eines Pipeline-Ereignisses",
    context: "Prototypdaten, kein Runtime-Ereignis",
  },
  {
    id: "l6",
    time: "Beispiel",
    source: "Tools",
    level: "Fehler",
    message: "Beispiel eines verweigerten Werkzeugzugriffs",
    context: "Prototypdaten, kein Runtime-Ereignis",
  },
];

const agents: Agent[] = [
  {
    id: "a1",
    name: "Beispiel Orchestrator",
    role: "Koordination",
    status: "offline",
    model: "Nicht verbunden",
    lastActivity: "Keine Live-Daten",
    tasks: 0,
    description: "Prototypzeile zum Testen von Auswahl und Detailansicht.",
  },
  {
    id: "a2",
    name: "Beispiel Recherche",
    role: "Informationsgewinnung",
    status: "offline",
    model: "Nicht verbunden",
    lastActivity: "Keine Live-Daten",
    tasks: 0,
    description: "Prototypzeile zum Testen von Auswahl und Detailansicht.",
  },
  {
    id: "a3",
    name: "Beispiel Archiv",
    role: "Wissenspflege",
    status: "offline",
    model: "Nicht verbunden",
    lastActivity: "Keine Live-Daten",
    tasks: 0,
    description: "Prototypzeile zum Testen von Auswahl und Detailansicht.",
  },
];

const memories: MemoryItem[] = [
  {
    id: "m1",
    subject: "Beispiel: Sprache",
    value: "Deutsch",
    tier: "Confirmed",
    confidence: 98,
    evidence: 3,
    provenance: "Prototyp-Fixture",
    created: "Beispieldatum",
    lastSeen: "Keine Live-Daten",
    superseded: false,
  },
  {
    id: "m2",
    subject: "Beispiel: Lokalität",
    value: "Lokale Ausführung bevorzugen",
    tier: "Candidate",
    confidence: 72,
    evidence: 2,
    provenance: "Prototyp-Fixture",
    created: "Beispieldatum",
    lastSeen: "Keine Live-Daten",
    superseded: false,
  },
  {
    id: "m3",
    subject: "Beispiel: Arbeitskontext",
    value: "Diagnose prüfen",
    tier: "Working",
    confidence: 100,
    evidence: 1,
    provenance: "Prototyp-Fixture",
    created: "Beispieldatum",
    lastSeen: "Keine Live-Daten",
    superseded: false,
  },
];

const tools: ToolItem[] = [
  {
    id: "t1",
    name: "Beispiel Dateisystem",
    type: "Lokal",
    status: "offline",
    description: "Prototypzeile zum Testen der Werkzeugansicht.",
    scope: "Nicht verbunden",
    lastUse: "Keine Live-Daten",
  },
  {
    id: "t2",
    name: "Beispiel Web-Anfrage",
    type: "Netzwerk",
    status: "offline",
    description: "Prototypzeile zum Testen der Werkzeugansicht.",
    scope: "Nicht verbunden",
    lastUse: "Keine Live-Daten",
  },
  {
    id: "t3",
    name: "Beispiel Terminal",
    type: "System",
    status: "offline",
    description: "Prototypzeile zum Testen der Werkzeugansicht.",
    scope: "Nicht verbunden",
    lastUse: "Keine Live-Daten",
  },
];

const automations: Automation[] = [
  {
    id: "u1",
    name: "Beispiel Systemprüfung",
    trigger: "Beispielzeitplan",
    lastRun: "Keine Live-Daten",
    status: "offline",
    runs: 0,
    description: "Prototypzeile zum Testen des nicht ausführenden Editors.",
  },
  {
    id: "u2",
    name: "Beispiel Indexpflege",
    trigger: "Beispielereignis",
    lastRun: "Keine Live-Daten",
    status: "offline",
    runs: 0,
    description: "Prototypzeile zum Testen des nicht ausführenden Editors.",
  },
];

const snapshot: JarvisSnapshot = {
  runtime: { state: "OFFLINE", detail: "Keine Live-Verbindung" },
  version: "Nicht verbunden",
  build: "Keine Runtime-Daten",
  metrics: [
    { label: "CPU", value: "Keine Live-Daten", detail: "Intel Core Ultra 5 245K" },
    { label: "GPU", value: "Keine Live-Daten", detail: "AMD Radeon RX 7900 XTX" },
    { label: "RAM", value: "Keine Live-Daten", detail: "Kapazität: 32 GB DDR5" },
    { label: "VRAM", value: "Keine Live-Daten", detail: "Kapazität: 24 GB" },
    { label: "Netzwerk", value: "Keine Live-Daten", detail: "Runtime nicht verbunden" },
    { label: "Aktive Agenten", value: "Keine Live-Daten", detail: "Runtime nicht verbunden" },
  ],
  performance: [],
  llmPerformance: [],
  gpuPerformance: [],
  model: {
    name: "Qwen3.5-35B-A3B-abliterated-Q3_K_M.gguf",
    family: "Qwen3.5",
    quantization: "Q3_K_M",
    context: "32768 Token",
    parameters: "Nicht angegeben",
    location: "Nicht angegeben",
    runtime: "llama.cpp",
    endpoint: "127.0.0.1:8080",
    gpuLayers: 999,
    batchSize: 512,
    ubatchSize: 128,
    temperature: 0.6,
    topP: 0.8,
    topK: 20,
    toolCalling: true,
    status: "offline",
  },
  activities,
  agents,
  skills: [],
  memories,
  tools,
  automations,
  voice: {
    input: "Kein Live-Signal",
    device: "pulse",
    sampleRate: 16000,
    channels: 1,
    outputBackend: "windows",
    tempPath: "/mnt/c/Users/Alex/AppData/Local/Temp/JARVIS",
    language: "Deutsch",
    wakeEngine: "Porcupine",
    wakeKeyword: "Aura",
    sttBackend: "Qwen3-ASR",
    sttModel: "Qwen3-ASR 0.6B INT8",
    sttRuntime: "sherpa-onnx",
    sttProvider: "CPU",
    sttThreads: 6,
    tts: "Chatterbox Multilingual V3",
    ttsEndpoint: "http://127.0.0.1:8765/tts",
    ttsConnectTimeout: "2 s",
    ttsReadTimeout: "60 s",
    ttsWarmup: false,
    ttsFallback: "Piper",
    ttsAlternative: "Kokoro, inaktiv",
  },
  platform: {
    host: "Windows 11 Pro for Workstations",
    linuxRuntime: "Ubuntu 24.04 unter WSL2",
    architecture: "x86_64",
  },
  hardware: {
    cpu: "Intel Core Ultra 5 245K",
    gpu: "AMD Radeon RX 7900 XTX",
    vramCapacity: "24 GB",
    ramCapacity: "32 GB DDR5",
  },
  services: [
    { name: "Main LLM", endpoint: "127.0.0.1:8080", configuration: "Konfiguriert" },
    {
      name: "Small LLM",
      endpoint: "http://127.0.0.1:8081/v1/chat/completions",
      configuration: "Konfiguriert, aktiviert",
    },
    { name: "Chatterbox", endpoint: "http://127.0.0.1:8765/tts", configuration: "Konfiguriert" },
    { name: "FLUX.2 Klein 4B", endpoint: "Port 8190", configuration: "Konfiguriert" },
    { name: "Memory SQLite", configuration: "Konfiguriert" },
    { name: "FAISS", configuration: "Konfiguriert" },
    { name: "Voice Runtime", configuration: "Konfiguriert" },
    { name: "WSL2", configuration: "Konfiguriert" },
    { name: "Windows Interop", configuration: "Konfiguriert" },
  ],
  memoryArchitecture: {
    stores: ["SQLite Faktenspeicher", "FAISS Semantikindex", "ContextWindow", "Interaction Cache"],
    features: [
      { name: "Konsolidierung", implemented: true },
      { name: "Decay", implemented: true },
      { name: "Autonomiebudget", implemented: true },
    ],
  },
  privacy: { gateImplemented: true, modesImplemented: true, desktopConnected: false },
  metricsRetentionDays: 180,
  subsystems: [
    { name: "Main LLM", status: "offline", detail: "Konfiguriert, Health unbekannt" },
    { name: "Small LLM", status: "offline", detail: "Konfiguriert, Health unbekannt" },
    { name: "Memory SQLite", status: "offline", detail: "Konfiguriert, Health unbekannt" },
    { name: "FAISS", status: "offline", detail: "Konfiguriert, Health unbekannt" },
    { name: "Voice Runtime", status: "offline", detail: "Konfiguriert, Health unbekannt" },
    { name: "Windows Interop", status: "offline", detail: "Konfiguriert, Health unbekannt" },
  ],
  devices: [
    {
      name: "Intel Core Ultra 5 245K",
      detail: "Konfiguriert, Auslastung unbekannt",
      status: "offline",
    },
    {
      name: "AMD Radeon RX 7900 XTX",
      detail: "24 GB VRAM, Auslastung unbekannt",
      status: "offline",
    },
    { name: "Arbeitsspeicher", detail: "32 GB DDR5, Auslastung unbekannt", status: "offline" },
    { name: "Audio", detail: "pulse, 16000 Hz, mono", status: "offline" },
  ],
};

export const prototypeAdapter: JarvisAdapter = {
  mode: "prototype",
  async getSnapshot() {
    return {
      phase: "prototype",
      data: snapshot,
      message: "Statische Konfiguration und klar markierte Prototypdaten",
      updatedAt: new Date().toISOString(),
    };
  },
  hasCapability() {
    return false;
  },
  async execute() {
    return { ok: false, phase: "not-implemented", message: "Nicht implementiert" };
  },
};
